// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAju6LyZKGZKE9NIqULKBD43B6J70h49wU',
    appId: '1:776269290873:web:183a48f1ac6374aafe23a8',
    messagingSenderId: '776269290873',
    projectId: 'gav-mobile-b2e2a',
    authDomain: 'gav-mobile-b2e2a.firebaseapp.com',
    storageBucket: 'gav-mobile-b2e2a.firebasestorage.app',
    measurementId: 'G-WHKE3C7RJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmPTVyw37n0KlIYk0jQwYAworO9vWn3RM',
    appId: '1:776269290873:android:12c64db793959f07fe23a8',
    messagingSenderId: '776269290873',
    projectId: 'gav-mobile-b2e2a',
    storageBucket: 'gav-mobile-b2e2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSG5mYrBHISIrZxuh4dG0lyRoB1THc7SI',
    appId: '1:776269290873:ios:856c4880571a6dfefe23a8',
    messagingSenderId: '776269290873',
    projectId: 'gav-mobile-b2e2a',
    storageBucket: 'gav-mobile-b2e2a.firebasestorage.app',
    iosBundleId: 'com.example.gavMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSG5mYrBHISIrZxuh4dG0lyRoB1THc7SI',
    appId: '1:776269290873:ios:856c4880571a6dfefe23a8',
    messagingSenderId: '776269290873',
    projectId: 'gav-mobile-b2e2a',
    storageBucket: 'gav-mobile-b2e2a.firebasestorage.app',
    iosBundleId: 'com.example.gavMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAju6LyZKGZKE9NIqULKBD43B6J70h49wU',
    appId: '1:776269290873:web:e256bf4ee58314e0fe23a8',
    messagingSenderId: '776269290873',
    projectId: 'gav-mobile-b2e2a',
    authDomain: 'gav-mobile-b2e2a.firebaseapp.com',
    storageBucket: 'gav-mobile-b2e2a.firebasestorage.app',
    measurementId: 'G-R8GWSZNP0B',
  );
}
